name: Android CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create Google Services JSON File
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON_DEBUG }}
      run: echo $GOOGLE_SERVICES_JSON | base64 -di > ./app/google-services.json

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew buildDebug

    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID_DEBUG}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT_DEBUG }}
        groups: testers
        file: app/build/outputs/apk/debug/app-debug.apk
